Fiap.Revisao.PS.MVC.Web/Models/Projeto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Revisao.PS.MVC.Web.Models
{
    public class Projeto
    {
        public int ProjetoId { get; set; }
        public string Nome { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime DataTermino { get; set; }
        public decimal Valor { get; set; }
        public Status Status { get; set; }

        //Relacionamento
        public Startup Startup { get; set; }
        public int StartupId { get; set; }
    }
}

Fiap.Revisao.PS.MVC.Web/Models/Startup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Revisao.PS.MVC.Web.Models
{
    public class Startup
    {
        public int StartupId { get; set; }
        public string Nome { get; set; }
        public decimal Faturamento { get; set; }
        public DateTime DataFundacao { get; set; }

        //Relacionamento
        public List<Projeto> Projetos { get; set; }
    }
}

Fiap.Revisao.PS.MVC.Web/Models/Status.cs
namespace Fiap.Revisao.PS.MVC.Web.Models
{
    public enum Status
    {
        Aguardando, Aprovado, Reprovado
    }
}

Fiap.Revisao.PS.MVC.Web/Controllers/ProjetoController.cs
using Fiap.Revisao.PS.MVC.Web.Models;
using Fiap.Revisao.PS.MVC.Web.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Revisao.PS.MVC.Web.Controllers
{
    public class ProjetoController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Buscar(string nomeBusca)
        {
            var lista = _unit.ProjetoRepository.BuscarPor(
                p => p.Nome.Contains(nomeBusca));
            return View("Listar",lista);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var projeto = _unit.ProjetoRepository.BuscarPorId(id);
            CarregarStartups();
            return View(projeto);
        }

        [HttpPost]
        public ActionResult Editar(Projeto projeto)
        {
            if (ModelState.IsValid)
            {
                _unit.ProjetoRepository.Editar(projeto);
                _unit.Salvar();
                TempData["msg"] = "Projeto Atualizado";
                return RedirectToAction("Listar");
            }
            else
            {
                CarregarStartups();
                return View(projeto);
            }
        }

        [HttpPost]
        public ActionResult Excluir(int id)
        {
            _unit.ProjetoRepository.Excluir(id);
            _unit.Salvar();
            TempData["msg"] = "Projeto Removido!";
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Aprovar(int id)
        {
            _unit.ProjetoRepository.Aprovar(id);
            _unit.Salvar();
            TempData["msg"] = "Projeto Aprovado!";
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Reprovar(int id)
        {
            _unit.ProjetoRepository.Reprovar(id);
            _unit.Salvar();
            TempData["msg"] = "Projeto Reprovado!";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            CarregarStartups();
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Projeto projeto)
        {
            if (ModelState.IsValid)
            {
                _unit.ProjetoRepository.Cadastrar(projeto);
                _unit.Salvar();
                TempData["msg"] = "Cadastrado!";
                return RedirectToAction("Cadastrar");
            }
            else
            {
                CarregarStartups();
                return View(projeto);
            }
        }

        [HttpGet]
        public ActionResult Listar()
        {
            var lista = _unit.ProjetoRepository.Listar();
            return View(lista);
        }

        private void CarregarStartups()
        {
            var lista = _unit.StartupRepository.Listar();
            ViewBag.opcoes = new SelectList(lista, "StartupId", "Nome");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

Fiap.Revisao.PS.MVC.Web/Controllers/StartupController.cs
using Fiap.Revisao.PS.MVC.Web.Models;
using Fiap.Revisao.PS.MVC.Web.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Revisao.PS.MVC.Web.Controllers
{
    public class StartupController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Startup startup)
        {
            if (ModelState.IsValid)
            {
                _unit.StartupRepository.Cadastrar(startup);
                _unit.Salvar();
                TempData["msg"] = "Cadastrado!";
                return View();
            }
            else
            {
                return View(startup);
            }            
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

Fiap.Revisao.PS.MVC.Web/Views/Projeto/Cadastrar.cshtml
@model Fiap.Revisao.PS.MVC.Web.Models.Projeto
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Projeto</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(p => p.Nome)
        @Html.TextBoxFor(p => p.Nome, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.DataInicio)
        @Html.TextBoxFor(p => p.DataInicio, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.DataTermino)
        @Html.TextBoxFor(p => p.DataTermino, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Valor)
        @Html.TextBoxFor(p => p.Valor, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Startup)
        @Html.DropDownListFor(p => p.StartupId , ViewBag.opcoes as SelectList,
            "Selecione", new { @class = "form-control"})
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
}

Fiap.Revisao.PS.MVC.Web/Views/Projeto/Editar.cshtml
@model Fiap.Revisao.PS.MVC.Web.Models.Projeto
@{
    ViewBag.Title = "Editar";
}

<h2>Atualização de Projeto</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    @Html.HiddenFor(p => p.ProjetoId)
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(p => p.Nome)
        @Html.TextBoxFor(p => p.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.DataInicio)
        @Html.TextBoxFor(p => p.DataInicio, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.DataTermino)
        @Html.TextBoxFor(p => p.DataTermino, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Valor)
        @Html.TextBoxFor(p => p.Valor, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Startup)
        @Html.DropDownListFor(p => p.StartupId, ViewBag.opcoes as SelectList,
            "Selecione", new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
}

Fiap.Revisao.PS.MVC.Web/Views/Projeto/Listar.cshtml
@model List<Fiap.Revisao.PS.MVC.Web.Models.Projeto>
@{
    ViewBag.Title = "Listar";
}

<h2>Lista de Projetos</h2>

@using(Html.BeginForm("Buscar","Projeto",
    FormMethod.Get, new {@class = "form-inline"}))
{
    <input type="text" name="nomeBusca" class="form-control"/>
    <input type="submit" value="Buscar" class="btn btn-primary" />
}
<hr />
<table class="table table-striped">
    <tr>
        <th>Nome</th>
        <th>Data de Inicio</th>
        <th>Data de Término</th>
        <th>Valor</th>
        <th>Status</th>
        <th>Startup</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.DataInicio</td>
            <td>@item.DataTermino</td>
            <td>@item.Valor</td>
            <td>@item.Status</td>
            <td>@item.Startup.Nome</td>
            <td>
                @Html.ActionLink("Editar","Editar", 
                new { id = @item.ProjetoId}, new { @class = "btn btn-primary btn-xs"})
                <button onclick="codigoProjeto.value = @item.ProjetoId" type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal">
                    Excluir
                </button>
                @if (item.Status == Fiap.Revisao.PS.MVC.Web.Models.Status.Aguardando)
                {
                    <button onclick="codigoProjeto1.value = @item.ProjetoId" type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myModal1">
                        Aprovar
                    </button>
                    <button onclick="codigoProjeto2.value = @item.ProjetoId" type="button" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#myModal2">
                        Reprovar
                    </button>
                }
            </td>
        </tr>
    }
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
            </div>
            <div class="modal-body">
                Deseja realmente excluir o projeto?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Excluir", "Projeto"))
                {
                    <input type="hidden" name="id" id="codigoProjeto"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
            </div>
            <div class="modal-body">
                Deseja realmente aprovar o projeto?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Aprovar", "Projeto"))
                {
                    <input type="hidden" name="id" id="codigoProjeto1" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-info">Sim</button>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
            </div>
            <div class="modal-body">
                Deseja realmente reprovar o projeto?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Reprovar", "Projeto"))
                {
                    <input type="hidden" name="id" id="codigoProjeto2" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-default">Sim</button>
                }
            </div>
        </div>
    </div>
</div>

Fiap.Revisao.PS.MVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro de Startup","Cadastrar","Startup")</li>
                    <li>@Html.ActionLink("Cadastro de Projeto","Cadastrar","Projeto")</li>
                    <li>@Html.ActionLink("Projetos","Listar","Projeto")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Fiap.Revisao.PS.MVC.Web/Views/Startup/Cadastrar.cshtml
@model Fiap.Revisao.PS.MVC.Web.Models.Startup
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Startups</h2>

@if(TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(s => s.Nome)
        @Html.TextBoxFor(s => s.Nome, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(s => s.Faturamento)
        @Html.TextBoxFor(s => s.Faturamento, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(s => s.DataFundacao)
        @Html.TextBoxFor(s => s.DataFundacao, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
}